// Reason codes for Validation Layer, Analyzers, and Decision Engine.
// Coded explanations for overlay and analytics.

export const ValidationReasonCode = {
  TIMESTAMP_MISSING_OR_NAN: 'V001',
  TIMESTAMP_BACKWARD: 'V002',
  RVFC_MISSING_OR_UNSUPPORTED: 'V003',
  READY_STATE_INVALID: 'V004',
  TICK_DELTA_INVALID: 'V005',
  DRIFT_INVALID: 'V006',
  PERFORMANCE_API_EMPTY: 'V007',
};

export const AnalyzerReasonCode = {
  DRIFT_EXCEEDS_HARD_THRESHOLD: 'D001',
  DRIFT_EXCEEDS_SOFT_THRESHOLD: 'D002',
  BIAS_UNSTABLE: 'D003',
  SIGMA_TOO_HIGH: 'D004',
  PIPELINE_WARMING: 'P001',
  WAITING_EVENT_ACTIVE: 'P002',
  SCHEDULER_OVERLOADED: 'P003',
  SCHEDULER_UNSTABLE: 'P004',
  DECODE_LATENCY_HIGH: 'S001',
  DROPPED_FRAMES: 'S002',
  FRAME_AGE_HIGH: 'S003',
  RVFC_STATUS_DEGRADED: 'S004',
  TRIANGLE_INCONSISTENT: 'T001',
  TRIANGLE_HIGH_DRIFT: 'T002',
  INCOMPLETE_TRIANGLE: 'T003',
};

export const DecisionReasonCode = {
  PIPELINE_NOT_READY: 'C001',
  SCHEDULER_OVERLOADED: 'C002',
  DECODER_UNHEALTHY: 'C003',
  FUTILE_SEEK_PATTERN: 'C004',
  DRIFT_BELOW_THRESHOLD: 'C005',
  ALL_CONSTRAINTS_PASS_SEEK: 'C006',
  ALL_CONSTRAINTS_PASS_HOLD: 'C007',
  TRIANGLE_OUTLIER_CORRECTION: 'C008',
  PLAYBACK_INACTIVE: 'C009',
  EXECUTION_IN_FLIGHT: 'C010',
  RECOVERY_GRACE: 'C011',
  HOLD_TO_OBSERVE: 'C012',
  PAIRWISE_OFFSET: 'C013',
};

export const ExecutionReasonCode = {
  COALESCED: 'E001',
  COOLDOWN_ACTIVE: 'E002',
  IN_FLIGHT_GUARD: 'E003',
  PRIORITY_PREEMPT: 'E004',
  EXECUTED: 'E005',
};
